### ISSUE TITLE
Big bug 

### ISSUE THREAD

**Issue by terrainwax** [FoxDenStudio/FoxGuard#10]
when we type a command like this /foxguard modify handler Exolord_ set owners block true they are nothing happening

**Comment by terrainwax** [comment]
i have the last update

**Comment by gravityfox** [comment]
...

Explain more?

**Comment by terrainwax** [comment]
when i do this command a blank line spawn in the chat and the handler was not modified

**Comment by gravityfox** [comment]
Fixed by FoxDenStudio/FoxCore@8d5ecc15.
