### ISSUE TITLE
Command Blocks aren't working

### ISSUE THREAD

**Issue by QuinellaMC** [FoxDenStudio/FoxGuard#109]
Hello,
First of all I want that you excuse me because I'm not English at all so my spelling could be false.

I installed FoxGuard et FoxCore on my server and I wanted to use some commands blocks for filling surfaces, but that don't work. I have set a permission on the world who says that we can't change block if we aren't owners. Please, tell me what I have to make

@+,

**Comment by ghost** [comment]
Hello,

Firstly, I apologize for taking so long to respond, GitHub emails had not been sending correctly.

Please join our discord if you still need help or have more questions: https://discord.gg/n4rbXKS
