### ISSUE TITLE
Hikari connection adder (pool HikariPool-8)" Id=5604 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject

### ISSUE THREAD

**Issue by viveleroi** [FoxDenStudio/FoxGuard#13]
Our beta sponge server crashed and best as I can tell, the foxguard db methods were involved. 

https://pste.me/#/B5xsM

**Comment by gravityfox** [comment]
This doesn't look like it's an issue with foxguard, because as far as i'm aware, my code is never executed. Can you get me the server log as well? The crash log only tells me where and how it crashed, not when.

**Comment by gravityfox** [comment]
Unable to reproduce.
