### ISSUE TITLE
Limit region sizes by permission

### ISSUE THREAD

**Issue by viveleroi** [FoxDenStudio/FoxGuard#14]
Users will need the ability to limit region sizes, so a player can't just claim some 10k^2 region. There should be some permission-based limits so that players are limited to increasingly larger regions as they rank up.

**Comment by gravityfox** [comment]
Do remember that this is a spiritual successor to WorldGuard, which means it IS an admin tool.

There will be an addon plugin in the future that will allow user claims, but for now just don't give users region permissions.

**Comment by gravityfox** [comment]
this is on the roadmap, but is so far away an issue doesn't make sense at the moment. I'll reopen this as a new issue in the future.
