### ISSUE TITLE
Database won't load... 

### ISSUE THREAD

**Issue by tacogerbil** [FoxDenStudio/FoxGuard#17]
I was playing using v0.15.1, saved on foxguard, shut down the server and didn't play for several days.  Before playing I updated to the new versions of FG and FC v0.16.1 and v0.6.2.. Now the regions do not exist in game.  FG list regions is blank and none of the rules I made apply in game anymore...  When I look in the world folder, in the foxguard folder; the regions and handlers are still there.  They are NOT empty files either.. each is around the range of 470k in size.... they just don't seem to load.

**Comment by gravityfox** [comment]
No longer relevant.
