### ISSUE TITLE
Protection disapears after a while

### ISSUE THREAD

**Issue by xanderindalzone** [FoxDenStudio/FoxGuard#25]
Hi, i managed to make the protections work, but the handler suddently as no effect after an hour more or less, like if the handler didnt have any permissions and every user could ignore them so the protection doesnt work..., it works again after rebooting the server but after an hour the same thing happens, i need help please, this is the only protection sponge plugin and i really need it :(

I'm using the most updated versión of the plugin, my server is in 1.8.9 using most updated sponge coremod.

**Comment by gravityfox** [comment]
That makes... no sense...

Also this is the first I've heard something like this...

Do you have a server i could check out?

**Comment by xanderindalzone** [comment]
it doesnt make any sense for me either, i'm using it on my pixelmon(4.2.1) server for minecraft 1.8.9, the ip is hcpixel.on.vg , ill try re-installing and deleting foxguard configs to see if that fixes the problem

**Comment by xanderindalzone** [comment]
ill stay online as much as i can, ill ask my friends if they can stay online too in case that im not there

**Comment by xanderindalzone** [comment]
its been 2 hours since i reinstalled everything... i'm not online but my friend says the protection is working fine... maybe that was the problem, that the plugin didnt upload correctly in first place, ill wait until tomorrow to see if still works, dont close this post yet just in case XD

**Comment by gravityfox** [comment]
Should no longer be relevant. I'll reopen it if it's still a thing. after the next release.
