### ISSUE TITLE
Foxguard API

### ISSUE THREAD

**Issue by hunter688** [FoxDenStudio/FoxGuard#26]
Will be possible add some API? I would like extend yours plugin.

Will be possible create some wiki page similar like this: http://wiki.sk89q.com/wiki/WorldGuard/Regions/API

For example  i would like to create regions, modify members and using special wand when click to ground get info about region (if present). Also when know Location in the world, would like get into if there any regions and can build for example.

Thanks.

**Comment by gravityfox** [comment]
There is already an internal API for interfacing with FoxGuard. That APi is just not documented because I keep changing things and breaking them in the process. Once I have the plugin roughly where I want it to be I'll start forming a well documented API
