### ISSUE TITLE
compiling issues

### ISSUE THREAD

**Issue by hunter688** [FoxDenStudio/FoxGuard#27]
1. please update submodule to commit ea1e75d70c2c3856fd3506e4c9168af7e818be22
2. fix mcmod.info issue: http://pastebin.com/7abcqLiq

Then will be FoxGuard compiled without errors.

**Comment by gravityfox** [comment]
I'm going to be an asshole and point out how cute this issue is.

Right now Foxguard is undergoing major refactors.

Whether travis can build the code right now is the least of my worries.

**Comment by hunter688** [comment]
oki
