### ISSUE TITLE
Several important (to me) flags are missing. 

### ISSUE THREAD

**Issue by jsnbrown1989** [FoxDenStudio/FoxGuard#28]
This might get trashed but I'm not sure of a better place to give you feedback. 

I have enjoyed Worldguard for around 3 years and have grown accustom to its flags. Moving to sponge has been concerning me with the absence of WG but a friend told me about your plugin and I am extremely excited. 

Having said that, 
The flags for entrance, exit, welcome messages, leave messages, pvp (allow/deny) and firespread are all important to me. I know this is just one person's opinion and you hear tons of people voicing their opinions as a plugin creator. I just feel like the flags could be flushed out a lot more. 

I know that filling them out is in your roadmap but I also see its on the bottom of the list and this concerns me. 

If you do this right, WG has no place on Sponge. We will be all using FoxGuard. You already have an amazing start and I enjoyed your youtube video. 

Keep up the work!!

**Comment by gravityfox** [comment]
Entrance and exit are already implemented See `playerenter` and `playerleave`.

Messages will be implemented as a controller, which actually allows you to create messages for ANY flag, including entering and leaving of course.

Finally, pvp and firespread are something that has been requested for awhile now. 

Pvp will be added as a flag.

Firespread will be part of the blockplace flag, but will use a specific handler/controller to deal with it.

Yeah... that's pretty much how it's going to go.

**Comment by jsnbrown1989** [comment]
Perfect man. You are great and thank you so much for responding to this. 

I'm definitely sticking with FoxGuard for my server here on out even if WG is ever released for sponge. 

I'm just hoping that you will keep developing it!
