### ISSUE TITLE
Foxguard Error  I need help

### ISSUE THREAD

**Issue by comdarksider** [FoxDenStudio/FoxGuard#29]
![untitled-1](https://cloud.githubusercontent.com/assets/18446159/14500283/a28514dc-01cb-11e6-9484-2352dac3ddb3.jpg)

I need help.

**Comment by gravityfox** [comment]
What version are you running, and on what spongeAPI version?

**Comment by gravityfox** [comment]
Closing because I never got additional details for this issue, and it's been 5 months.
