### ISSUE TITLE
Denying passive events seems to be buggy if not nonfunctional this version.

### ISSUE THREAD

**Issue by WryWolfy** [FoxDenStudio/FoxGuard#30]
As the title says, denying passive events seems to be buggy if not nonfunctional this version.
I'm specifically referring to ice forming - after setting a simple handler's passive status to 'deny' and linking it to _sglobal, ice still forms in cold biomes.  Just a couple versions of this plugin ago this feature worked just fine.

I'm very anxious for this to be addressed, and thank you for your time.
~ WryWolfy

P.S.: I'm using version 0.18.0-249 of FoxGuard and FoxCore version 0.8.0-103-server

**Comment by gravityfox** [comment]
Any errors in log? What version of spongeAPI are you using?

**Comment by WryWolfy** [comment]
Checked the logs - no errors whatsoever.  I'm using SpongeAPI 4.1.0 - specifically "spongeforge-1.8.9-1808-4.1.0-BETA-1286.jar".

Thanks for your time,
~ WryWolfy

**Comment by gravityfox** [comment]
I haven't actually touched any of that code, but i'll definitely take a look for you.

As of right now, sponge is going through some major event refactors, so it might not actually be an issue on my side. I'll look into it.

**Comment by WryWolfy** [comment]
Thank you so much either way, I really appreciate it!

Keep up the good work,
~ WryWolfy

**Comment by WryWolfy** [comment]
As of the latest sponge release and the latest Foxguard+Core releases this remains a problem for me.  Any idea why?

Thanks,
~ WryWolfy
