### ISSUE TITLE
Flag blockattack dont work with priority

### ISSUE THREAD

**Issue by Flashback083** [FoxDenStudio/FoxGuard#32]
Hello ! The flag Block Attack have a little problem with the priority of handler :p 

I set this perm handler for global worldregion : 
https://gyazo.com/aa653af183c396eadd8bc6a14f1d0bba

I set this perm handler for "claim worldregion" : 
https://gyazo.com/f65df5b849d20337c586843709ff7275

The user can place block but not attack 

if i set break deny instead of block attack , its work a player can break in their claim.
But i need use blockattack ^^'

Any idea ? 
Thanks !

**Comment by gravityfox** [comment]
Non-issue from the looks of it. You need to explain your problem better.

**Comment by Flashback083** [comment]
What you dont understand ? I dont know what i must explain better ><

**Comment by gravityfox** [comment]
Actually, you need to add clickblock to owner and member access.
`block` is NOT a parent of `blockclick`, although i can make it so.

**Comment by Flashback083** [comment]
Okai, i think im just noob.
Sorry for use your time, and thanks >w<

**Comment by gravityfox** [comment]
Yeah i couldn't understand your english, so i just tried to figure out what you were trying to accomplish.

Also no worries. Foxguard is a confusing plugin. You're not the only one who has trouble with it.
