### ISSUE TITLE
No permissions in a region

### ISSUE THREAD

**Issue by Flozian** [FoxDenStudio/FoxGuard#33]
Hi @gravityfox  ~ 

I contact u today, for report a bug or... something like that c: . We have a server Minecraft with a friend, a pixelmon server [With Pokemons, yay !] & actually when we try to create a region and only let players use the command /spawn [So we don't let them, place blocks & open chests for example.]. There's a matter, because players & OP-players can't do nothing except /spawn in this region. But normally, the OP one should be able to do all the commands they want & pass the guard, shouldn't them ? Can we use a command or something for give some access in this region to the admins ? 

We use this version : FoxCore-0.8.1-108.jar
                                  FoxGuard-0.18.0-249.jar

& I have two little more questions for u : - Do we need the mod client ? 
                                                               - Do we need to put the server mod, on the server or players need to have it too ? 

Thanks for ur answers ~

**Comment by gravityfox** [comment]
This is a question. Ask questions on the forums only.
