### ISSUE TITLE
Flag(s) "playerpass" not working.

### ISSUE THREAD

**Issue by MarkL4YG** [FoxDenStudio/FoxGuard#35]
I just noticed that the flag(s) "playerpass" do not deny you anything when set to deny.

No error messages or whatsoever: But if I had to, I would guess this is due to the recent changes to the teleportation API of Sponge.

Spongev.:  spongevanilla-1.8.9-4.1.0-BETA-332.jar
FGv.: FoxGuard-0.18.0-249.jar
FGCv.: FoxCore-0.8.1-108

**Comment by gravityfox** [comment]
Closing because old version. Also works in my devspace.
