### ISSUE TITLE
How to delete a region?????????????

### ISSUE THREAD

**Issue by SourcePowered** [FoxDenStudio/FoxGuard#42]
`/foxguard delete <region [--w:<world>] | handler> <name>`
Right?

OK, I use:

/fg delete myregion  -- ERROR
/fg delete myregion world -- ERROR
/fg delete myregion --w:world -- ERROR
/fg delete myregion myregion -- ERROR
/fg delete myregion [--w:<world>] -- ERROR
ERRRRRRRRRRRRRRROR!!!!!!!!!!!!!!!!!!!!!!
............More and more.

OH MY GOD!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Can you tell me how to delete a region??? This is so... I have nothing to say.

**Comment by Inscrutable** [comment]
Have you tried ``/fg delete region myregion``?

**Comment by gravityfox** [comment]
Closing issue because this:

A: belongs on the forums

B: is already documented in the wiki.

C: could have probably been solved by reading the usage for the command, which is shown if the command fails.

D: could have probably been solved by using tab completion for the command.
