### ISSUE TITLE
Players can still break blocks...

### ISSUE THREAD

**Issue by jckani** [FoxDenStudio/FoxGuard#44]
Everything works , handlers , define regions , but Players still can break blocks. 
Flags for Default are : change blocks :false 
                                   break blocks :false 

And i cant use /fg wand   error:.... No value present

**Comment by gravityfox** [comment]
is this a vanilla server? if so, i'll take a look at it.

**Comment by jckani** [comment]
We are running Pixelmon on it ...

Can you tell me what files we need from FoxCore releases , cause there are more .jar files. 

And do you know why '/fg wand' doesnt work ?
