### ISSUE TITLE
regions protected from block break and/or place can not use buttons switches pistons

### ISSUE THREAD

**Issue by wiesshund** [FoxDenStudio/FoxGuard#49]
if you put a handler in your region that disallows placing or breaking blocks
Anyone who is not owner will not be able to operate anything that uses a block break or place.
additionally i have found that on the piston, even the owner can not operate it because 2 events in the retract sequence are triggered by the entity None.

The only way to let them retract is to set passive allow, which appears the area to be damaged
by things not the player (like creepers exploding)

In effect, players who are not owners of a region can not interact with many things in it

I have not gone through and tested all blocks, but it appears to affect anything that has moving parts

**Comment by gravityfox** [comment]
Closing because i repeatedly said this is NOT something i can do something about, and this is the fault of Sponge.
