### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by ziceptor** [FoxDenStudio/FoxGuard#50]
CommandCreate.java line 155

`"Worldr" : "R") + "egion created successfully"));`

**Comment by gravityfox** [comment]
What kind of an issue is this...?

**Comment by ziceptor** [comment]
not a typo "Worldr"

**Comment by gravityfox** [comment]
no...?

It's selecting between lowercase and uppercase R. That's why...

The code is fine... I'm not sure why you made an issue...
