### ISSUE TITLE
Denying players permission to build in an entire world?

### ISSUE THREAD

**Issue by ghost** [FoxDenStudio/FoxGuard#51]
I've been thinking about how to do this, and the best idea I can come up with is to use an elevation region from the bottom of the world to the top and set a handler that doesn't allow building. I was wondering if there's a way to register a handler to an entire world instead of just making a region that encompasses the entire world, because I thought it might be simpler and use less resources.

**Comment by gravityfox** [comment]
I'm not sure if you were aware, but FoxGuard automatically generates a Server Global region `_sglobal` and a world global region `_wglobal` for every world.

I'm not entirely sure how you missed them when using `/fg list regions`, considering they're highlighted in pink and yellow respectively.

basically just link a handler to the world global region for the world you want to deny building, or to the server global region if you want to deny it on the whole server.

Something like this: `/fg link _wglobal myhandler`

Anyway hope that helps. Also, the issue tracker isn't a place for questions, please use Sponge Forums or some kind of private/direct message.
