### ISSUE TITLE
[Minor]onClicks missing spaces

### ISSUE THREAD

**Issue by MarkTwoFive** [FoxDenStudio/FoxGuard#52]
While testing the new update I realized that some onClick-TextActions miss a space here and there which results in invalid commands.

Edit: Removed falsely reported code locations... sorry for that :/

**Comment by gravityfox** [comment]
Umm.... except those two work COMPLETELY FINE.

FGUtil.java#genWorldFlag(), puts a space in if it needs to.

Apparently people are now finding "bugs" in my code just by reading it, like in #50...

So i'm going to ask... Are there any on clicks that you have actually tried IN-GAME, that are broken? Those are the only ones that really matter.

**Comment by MarkTwoFive** [comment]
Well, I might have pointed to the wrong lines then... sorry for that.
Yes I did discover this in-game, I just thought that these were the sources.  

---

Reproduce:
- `/fg here`
- click `SGlobal : ...`
  ->
  "Not a valid category!" `region_sglobal`

**Comment by gravityfox** [comment]
ahh so you did catch something... thank you

**Comment by gravityfox** [comment]
Did you find anything else or no?

**Comment by MarkTwoFive** [comment]
I didn't run into another thing like this but to be honest, I didn't try every command :)
I'll respond to this issue should I encounter something like this again.

**Comment by gravityfox** [comment]
kk i'll close for now.
