### ISSUE TITLE
root debuff block decay =deny

### ISSUE THREAD

**Issue by WillPowerCraft** [FoxDenStudio/FoxGuard#53]
that protect leaves blocks (from my awesome wood) but infinitly generate drop from that blocks like if it decay allow.

i use your plugin on my server on 1.11 =)

thats funny what players can found on spawn free apples and leaves like in realistic wood, but that generate to many item entitys...

how possible stop it now? or that is bug what will fix future?

**Comment by gravityfox** [comment]
It's a sponge bug. I'll go bother their devs when i have time.
