### ISSUE TITLE
infinity TNT explosions

### ISSUE THREAD

**Issue by WillPowerCraft** [FoxDenStudio/FoxGuard#55]
1. create worldregion with handler flags:
interact block allow
block place deny
block break deny

put in that region as owner tnt block

and come as other player (not owner and not op) and activate tnt block from flint&steel
that lauch intinity tnt explosions in that tnt block.

and if near placed some redstone - that make dupe redstone from every tnt explosion near.

//but what i as OP and not as owner handler cant put blocks from creative or from console commands thats SUCH AWESOME!!!

**Comment by gravityfox** [comment]
@Inscrutable named these TNT flowers.

That means we already know about it.

It's also... YET AGAIN... a sponge bug.

**Comment by gravityfox** [comment]
Sadly this is no longer a ~~feature~~ bug, so i must close this :P
