### ISSUE TITLE
visible positions blocks from wand

### ISSUE THREAD

**Issue by WillPowerCraft** [FoxDenStudio/FoxGuard#56]
on your tutorial video every block what u put from wand visually marked as white colored limpid block.

when i marking blocks from wand with any choosed color i never see that visually marked.

im using command /fg wand position white

how i can make that marked blocks visually effect?

same spongevanilla for 1.11

//im sorry for bad english

**Comment by gravityfox** [comment]
The overlay is a forge client mod. If you don't have it installed, of course nothing will show up.

Sponge plugins aren't exactly MAGIC.
