### ISSUE TITLE
Foxguard causing crash during the boot

### ISSUE THREAD

**Issue by jules552** [FoxDenStudio/FoxGuard#58]
Hey,
When I'm trying to start  my server on the latest version of spongeforge (in 1.11), my server crash, I have this in the crash-report:

http://pastebin.com/BvrXCZx4

For me this problem is causing by Foxguard, if not, sorry for the issue ;)
Have a good day !

**Comment by WillPowerCraft** [comment]
good for me that i using vanilla.... have some errors on launch but not critical, plugin and server working fine (as i can see)

**Comment by gravityfox** [comment]
okay so the problem here is that you're using the unlabled jar file.

You need the -server.jar file
