### ISSUE TITLE
Could not pass ExplosionEvent$Detonate$Impl to Plugin{id=foxguard

### ISSUE THREAD

**Issue by ziceptor** [FoxDenStudio/FoxGuard#59]
Obtain, with the explosion of the creeper outside the region: http://pastebin.com/LnMbFx4N

**Comment by gravityfox** [comment]
Does this happen often?

Can you screenshot the result of `/fg ls r` and `/fg ls h`

**Comment by ziceptor** [comment]
Rarely. I play two children. We should ask the owners of the production servers.

[/fg ls r](https://cloud.mail.ru/public/Esfd/YZcua179E)
[/fg ls h](https://cloud.mail.ru/public/Kyyb/955DkNoaU)

**Comment by gravityfox** [comment]
Hmm okay.... 

That's even weirder...

I need to take harder look at this...

**Comment by ziceptor** [comment]
Edit: At each explosion of a creeper.

**Comment by gravityfox** [comment]
I think i found the issue.

I wasn't doing an isEmpty check.

I'll close for now. If the next version does this i'll reopen

**Comment by ziceptor** [comment]
Ok. [Video](https://cloud.mail.ru/public/GUqj/scU1JkSAt)
