### ISSUE TITLE
SpawnEntityEvent

### ISSUE THREAD

**Issue by AdnanMia** [FoxDenStudio/FoxGuard#60]
Whenever I set a flag to stop mobs from spawning, an error spams the console.

`11.12 04:17:49 [Server] ERROR [Sponge]: Could not pass SpawnEntityEvent$Spawner$Impl to Plugin{id=foxguard, name=FoxGuard, version=0.20.2-api5-347, description=A world protection plugin built for SpongeAPI. Requires FoxCore., url=https://github.com/FoxDenStudio/FoxGuard, authors=[gravityfox], source=mods/foxguard-0.20.2-api5-347.jar}`

Minecraft: 1.11
SpongeAPI: 6.0.0-SNAPSHOT-af15769
SpongeVanilla: 1.11-6.0.0-BETA-183

I'm using the latest version of FoxGuard.

Help, would be appreciated. 
Thanks

**Comment by liach** [comment]
You should install FoxCore.

**Comment by AdnanMia** [comment]
I've got foxcore-0.10.1-api5-202-server.jar installed already.

**Comment by liach** [comment]
Does it have a stack trace?

**Comment by Adnan1234** [comment]
https://paste.ubuntu.com/23611904/

There we go. I think that's it.

**Comment by ghost** [comment]
What handler are you using?

**Comment by AdnanMia** [comment]
The error that I'm getting is https://paste.ubuntu.com/23611988/
(All that's showing in console)

It's occurred when I have flagged my handler, namsmaps to stop the spawning of mobs. Despite applying the flag, mobs still spawn in the region too. 

It prints that error to console every minute or so.

**Comment by ghost** [comment]
Is there a stacktrace with that error?
Or is it literally just printing out that?

**Comment by d4rkfly3r** [comment]
Or is it literally just printing out that?

**Comment by AdnanMia** [comment]
It was literally printing that error out every so often until I removed the mob spawn flag.

**Comment by ghost** [comment]
Found one potential cause, I'll have @gravityfox take a look when he gets back.

**Comment by ghost** [comment]
Actually I'm 99% sure that #59 is also caused by this.

**Comment by AdnanMia** [comment]
Thanks, hope you guys are able to fix this soon.

**Comment by vectrixdevelops** [comment]
I posted a full stack trace to @gravityfox, this will require some further testing.

**Comment by gravityfox** [comment]
I found the bug. As it turns out, it was just two places where i had `null` instead of `Tristate.UNDEFINED`.

Either way, it should be good now.

EDIT: I also want to point out that this is probably the saddest bug i've ever left in my code. It was almost impossible to figure out, because it was so small.
