### ISSUE TITLE
not sure if this is incomplatible

### ISSUE THREAD

**Issue by Sitherious** [FoxDenStudio/FoxGuard#72]
i keep getting this console spam and i am unsure if its an issue with foxguard or is it incompatible with a plugin or mod

https://paste.ubuntu.com/23846086/

**Comment by gravityfox** [comment]
I think I already fixed that bug, but i'm not sure why it was happening.

**Comment by Sitherious** [comment]
Not sure what's causing it, it happens allot tho and no other errors appear in the logs.

**Comment by gravityfox** [comment]
Actually I know exactly what the problem is, and i fixed it in code. I just haven't released it.

**Comment by Sitherious** [comment]
ok :) ill wait for the new one when it is released and thankyou.
