### ISSUE TITLE
Issues createing regions

### ISSUE THREAD

**Issue by EmanYm** [FoxDenStudio/FoxGuard#73]
Greetings.

I don't know if I'm missing something, doing something wrong or if I have a config not set right.

When I type "/foxguard create region <name>" it will not tab any suggestions, and get the error "**Must Specify a type!**" if I add 'rectangular' and press enter.
However when I type "/foxguard create **worldregion** <name>" it suggests rectangular, cuboid and elevation when I tab.
"_A world-global region applies to an entire world, and there is one for each world._" (from the _Quick Start_ guide)

According to [this](https://github.com/FoxDenStudio/FoxGuard/wiki/Rectangular-Region) page, I don't need to make it a worldregion.

I just want a simple, one-block column space that can be protected from players that don't have the permission to enter that space.

Versions:
SpongeForge v5.1.0β2086
FoxCore v0.10.3-200
FoxGuard v0.20.2-API5-β347

**Comment by Inscrutable** [comment]
That page was outdated. Make a worldregion.
The world and global regions already exist as __wglobal_ and __sglobal_ by default.

**Comment by EmanYm** [comment]
So it's worldregion or nothing.  Got it!

Now where did I put that thumb's up icon...
