### ISSUE TITLE
SpongeEventFactoryUtils Error

### ISSUE THREAD

**Issue by Aphex124** [FoxDenStudio/FoxGuard#78]
Hi, 
Every time I load the server and try to make a handler, I get a SpongeEventFactoryUtils error. I've disabled all the mods on my server, deleted the world, and eventually tried a clean install, with the error still popping up. I don't really know what else to say so.. [Heres the pastebin](http://pastebin.com/v9sgcieH)

Used with:
FoxCore v0.10.3-208
FoxGuard v0.20.2-api5-347
Sponge v1.10.2-2221-5.2.0-BETA-2215
Forge v12.18.3.2215

**Comment by gravityfox** [comment]
known issue and being patched currently

**Comment by ghost** [comment]
@Aphex124 Try this build https://github.com/FoxDenStudio/FoxGuard/releases/tag/v0.20.5-untested-hotfix

Please let me know if this fixes the issues and/or causes more. 

(Don't forget to backup first)

**Comment by Aphex124** [comment]
@d4rkfly3r I will test within a few hours, but I have fixed the issue by building the API6 branch of Foxguard and using that in place, and it seems to be working flawlessly :)

**Comment by ghost** [comment]
Yeah, the API 6 branch is the fixed branch, so the release posted above should just be the build of it.

**Comment by ghost** [comment]
Closing as this issue seems to have been fixed with the latest hotfix.
