### ISSUE TITLE
Possible to deactivate unload worlds?

### ISSUE THREAD

**Issue by Hodel1** [FoxDenStudio/FoxGuard#84]
...

**Comment by ghost** [comment]
Can you please post the entire log (via gist or pastebin, or similar).  Or **attach** the log file to your comment.

**Comment by Hodel1** [comment]
...

**Comment by ghost** [comment]
Yeah there is.

```java
[22:03:57] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.world.ChunkDataEvent$Save@42f26ed:
java.lang.NullPointerException
```

there should be more to this error.

**Comment by Hodel1** [comment]
...

**Comment by gravityfox** [comment]
Foxguard only unloads it's own data when sponge starts to unload a world. Foxguard has literally nothing to do with this. It's not even in the stacktrace for crying out loud.
