### ISSUE TITLE
Immortal Pixelmon mob spawn

### ISSUE THREAD

**Issue by AsylumDreams** [FoxDenStudio/FoxGuard#86]
Apologies for the lack of information here at the moment - literal 4 minutes before I need to run to work - but just flagging this as it seems like a basic clash.

 FoxGuard region set to deny mob spawns - works fine, no spawning of mobs - pixelmon or natural MC - after a few minutes idle time compared to a dozen or so before the limit was enabled.

Pixelmon spawn grass triggers battles fine. Walking or idling in it initiates a fight - but no pokemon are released for this.  Or at least no models are displayed. The GUI switches into the battle display and all works fine, but there is no KO, just the fighting continuing as if there was still HP to deplete.

Unsure of whom to send this to, so gifting it to you both ^_^

Pixelmon 2.1.4 
FG:0.20.5 Hotfix367
SpongeAPI 5.2.0 snapshot - a3257a0
SForge 2281-Beta 2274
MForge 12.18.3.2281.

**Comment by gravityfox** [comment]
Closing because of the currently legal status of pixelmon.

I not particularly fond of writing compatibility code for a mod that isn't supposed to exist.
