### ISSUE TITLE
PlayerMoveListener preventing players from being garbage collected

### ISSUE THREAD

**Issue by Katrix** [FoxDenStudio/FoxGuard#89]
`last` field in `PlayerMoveListener` is preventing players that have logged off the server hours ago from being garbage collected. Would is be possible to free the player object when they log out?

**Comment by ghost** [comment]
So theoretically you are correct, having a non WeakReference to a player object, would prevent it from being GCd. There are a few things to consider though, the first being that sponge already holds the player object somewhere (even though it could be changed). If that is changed, we will update it to a WeakReference. The other thing is that the player object is tiny compared to most of the other Minecraft stuff.

**Comment by Katrix** [comment]
Looking at a heap dump of a running server, FoxGuard is the only thing referencing at least this specific player. Also, don't know how much it matters here, but the reason I noticed this was because of another issue with garbage collection where the player object grew to roughly 1 gb in size. While using a weak reference here wouldn't fix that issue, and I'm working on finding out the specifics of the leak, using a weak reference here will at least make it more tolerable as all that garbage will be freed at some point.

**Comment by gravityfox** [comment]
A player object one gigabyte​ in size is impossible. Player has a reference to a world object. Your heap dump is probably trying to give you a Max theoretical accessible memory, in case the object contains references to single reference objects. The actual player object is tiny, and is NOT taking up a gigabyte of memory.

**Comment by Katrix** [comment]
As I said, another GC issue where stuff isn't freed like it's supposed to. Yes I know that it's the actual size of the player object, as if it wasn't, I wouldn't have problems with out of memory errors every 12 hours on the server.

![Image](https://user-images.githubusercontent.com/11007080/27251190-42fa7b8c-5342-11e7-9a85-c991affaaa66.png)

**Comment by ghost** [comment]
Please expand the tree a few more, screenshot and I'll review.

**Comment by ghost** [comment]
Can you please tell us in what class that data is actually sitting? We think we know what's causing it, and we think it is a stupid reference quirk with sponge.  We can most likely make a fix for this, but if it is Sponge causing it, we want to make sure to report it.

**Comment by Katrix** [comment]
Just classloaders beyond that point. As for the actual cause of that, created an issue for it some time ago. https://github.com/SpongePowered/SpongeForge/issues/1577. 

Was just yesterday that a realized that a player that hadn't been on the server for maybe 18 hours was the cause of most of the memory usage. In that sense FoxGuard has been helpful keeping it around so I could find it :P.

![Leak](https://user-images.githubusercontent.com/11007080/27252092-bb118bc0-5355-11e7-9378-b7a99dec9d3c.png)

**Comment by gravityfox** [comment]
The thing is, Sponge doesn't create a bunch of player objects. All player objects are actually EntityPlayerMP objects, which are provided by minecraft server. Minecraft server is pretty bad about letting go of these too. Honestly it's not something worth fixing. The player object itself is not using that much memory. If it's holding onto something that is, there is another completely separate bug going on.

**Comment by gravityfox** [comment]
Welp. After looking at this a bit i've decided it's an issue that is way more complicated than is worth thinking about when i could just use a weakreference. So i'm going to do that, cause there's no reason i should contribute to the problem.

**Comment by gravityfox** [comment]
This has been fixed as of v0.22.0

Thank you @Katrix for pointing this out to us.
