### ISSUE TITLE
add permission to wiki

### ISSUE THREAD

**Issue by terrainwax** [FoxDenStudio/FoxGuard#9]
i have listed all permission of your plugin 
 /fg handlers priority : foxguard.command.modify.objects.handlers.priority
 /fg modify : foxguard.command.modify.objects.modify
 /fg delete : foxguard.command.modify.objects.delete
 /fg detail : foxguard.command.info.objects.detail
 /fg list : foxguard.command.info.objects.list
 /fg create : foxguard.command.modify.objects.create
 /fg enable/disable : foxguard.command.modify.objects.enabledisable
 /fg link : foxguard.command.modify.link.add
 /fg rename : foxguard.command.modify.objects.rename
 /fg save : foxguard.command.save
 /fg remove : foxguard.command.modify.link.remove
 /fg about : foxcore.command.info.about
 /fg add : foxcore.command.state.add
 /fg debug : foxcore.command.debug.debug
 /fg flush : foxcore.command.state.flush
 /fg position : foxcore.command.state.add.position
 /fg state : foxcore.command.state.state
 /fg subtract : foxcore.command.state.subtract
 /fg test : foxcore.command.debug.test
 /fg wand : foxcore.command.wand
it's all and when you thinks made the update for beta ?

**Comment by gravityfox** [comment]
I find it funny that the foxcore commands are in there too.

And i'll have an update for beta soon now.

I just needed to rewrite the command parser (again).

**Comment by gravityfox** [comment]
Okay I added a page now.
