### ISSUE TITLE
Is fg (b)locking save locations?

### ISSUE THREAD

**Issue by MarkTwoFive** [FoxDenStudio/FoxGuard#90]
It seems that whenever I run FoxGuard on my servers after some time the server fails to save the levels leaving behind [this helpful message](https://hastebin.com/qadanobika.md) for every loaded level.  
I've played around enabling/disabling plugins and also different SpongeVanilla versions.  

That left me with a blank server where only fg is installed which had the exact same issue.  
At first I didn't want to submit this but with progressing fg/SV versions this didn't change.  
Thus: Is there any possibility that fg/fc locks the save locations e.g. when saving it's configs without lifting the lock?

**Comment by gravityfox** [comment]
I mean... maybe...? but i don't see how... There's nothing i'm doing that should be locking the directory.

In every file system i've ever worked with, locking a file in a directory never locks the parent directory itself, only the file in question. Perhaps your file system is weird.

Pray tell, what OS are you using, and what file system are you using...?

**Comment by MarkTwoFive** [comment]
Oops, totally forgot that: Encountered on Ubuntu 16(ext3), 17(ext4) and Windows 10(ntfs).  
I feel just as weird about that but the issue doesn't appear when fg is not installed while it also appears with only fg installed 🤔
I only tested using SpongeAPI 5 versions though

**Comment by ghost** [comment]
@MarkL4YG:

If you don't mind, can you please post your entire log file.  
This is partially for us to be able to 100% verify versions, and other important system details.

Also, are you running this on a self hosted server, or one with a server hosting company?

**Comment by MarkTwoFive** [comment]
The Ubuntu OSes run on a dedicated server and the Windows version on my desktop.

Sure I just need to either search for the logs or "reproduce" them - either way I'll attach one/them then.
Edit: I'm going to produce a new one, the archived logs seem to be stripped of debugging information

Just to be clear - the issue does not appear on each run and also only appears after some time (mostly hours) has passed.

**Comment by gravityfox** [comment]
I have personally never seen this issue, and Sponge Community Server, as well as many other servers, can run FoxGuard for very extended periods of time without ever encountering this.

I wonder if there's something else wrong.

**Comment by MarkTwoFive** [comment]
You can guess that I already spent days on searching for any other possible reason... of course that doesn't rule out that there might be something wrong with MC/Sponge in these particular setups.  

The closest explanation possible - I found - is a file header limit under *nix but that wasn't yet reached on our servers and surely doesn't apply to Windows so I ruled that out.

**Comment by gravityfox** [comment]
what if it's the sponge version you're using that's broken. It might help if you told us which version you're on.

**Comment by MarkTwoFive** [comment]
I randomly picked versions <= build 384 of SpongeVanilla (5.X) higher builds are currently broken.

**Comment by ghost** [comment]
So after testing on multiple servers for the last few hours, I have not been able to reproduce this error. 
I have tried Ubuntu Server (16.04.2 LTS & 17.04), CentOS (6 & 7), and Windows Server (2012 & 2016).

Are you using any sort of file managers or antivirus?  This includes thing like software level RAID.

If not, we can't help any more unless we get a full log from when it fails.

**Comment by gravityfox** [comment]
Oh.... Antivirus could definitely be an issue. While foxguard should never lock those directories, there are antiviruses that WILL in response to what foxguard does.

**Comment by MarkTwoFive** [comment]
I will look into that but I don't suspect a clear result as my Windows Antivirus is brain.exe ^^

@gravityfox can you specify the actions fg performs which may trigger AV responses maybe I can look for those in my search then?

**Comment by gravityfox** [comment]
I honestly don't know... actually... hold on a sec... you said that this happens after the server has been running for a while right...? FoxGuard does not automatically do file access... You have to run a command or shut down the server...

I'm really starting to be suspicious there's something else going on here.

**Comment by MarkTwoFive** [comment]
Well ... yes the server needs to have run some time until this pops up... I'm just as unsure which is why I waited nearly two months until I contacted you in order to analyze, check and google for what could cause this.  

I'm going to test further of course and if you don't know anything in fg that could cause this I'm feeling fine to just let this issue sit until I figure out more than just hints.

**Comment by MarkTwoFive** [comment]
This issue has been resolved. It appears that the reason was another plugin which created another dimension asyncronously which Minecrafts save handler class doesn't seem to support.
