### ISSUE TITLE
Crash in new Sponge version

### ISSUE THREAD

**Issue by ghost** [FoxDenStudio/FoxGuard#91]
Crash: https://pastebin.com/BpsRdbi2
After I update to the Sponge new version (1.10.2-2281-5.2.0-BETA-2597) this crash appers :/

**Comment by ghost** [comment]
I can't be one hundred percent sure, but that doesn't look like it is a versioning issue. It rather looks like the database file become corrupted or lost access permissions when you upgraded.  

Please check that the server folders are set to the right permission settings.

**Comment by gravityfox** [comment]
Wheee mapdb errors when trying to read RAFs.

Irrelevant with storage overhaul.
