### ISSUE TITLE
Not preventing bucket interaction

### ISSUE THREAD

**Issue by 0Fox** [FoxDenStudio/FoxGuard#92]
If set flag to "secondary block interaction =false" and "block =false" player can get water in bucket from block of water BUT block stays. Probably works with lava too..
Its bug or i'm too stupid to understand how flags work..

**Comment by Snez0kRU** [comment]
Sponge: 1.10.2-2281-5.2.0-BETA-2597
Forge: 2281
fox Guard: foxguard-0.20.idk-api5.2-371-server
foxcore-0.10.4-api5.2-222-server

I have this bug too, pls fix it.

**Comment by gravityfox** [comment]
This was a very old sponge bug.

If this issue comes up, please make a new issue
