### ISSUE TITLE
FoxGuard can't control the minecraft:item_frame

### ISSUE THREAD

**Issue by MrSeven590** [FoxDenStudio/FoxGuard#97]
spongeforge-1.10.2-2477-5.2.0-BETA-2793
foxcore-0.10.4-api5.2-222-server
foxguard-0.20.idk-api5.2-371-server

I set the default group to block =deny

and players also can break the frame

**Comment by gravityfox** [comment]
That's because item frames aren't blocks.
use `entity hanging =deny`
